# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_team_alias'),
        ('auctions', '0006_auto_20170301_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Batting_Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.CharField(default=0, max_length=3)),
                ('balls', models.CharField(default=0, max_length=2)),
                ('fours', models.CharField(default=0, max_length=2)),
                ('sixes', models.CharField(default=0, max_length=2)),
                ('retired', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_batsman', to='auctions.Sold_Player')),
            ],
        ),
        migrations.CreateModel(
            name='Bowling_Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.CharField(default=0, max_length=3)),
                ('wickets', models.CharField(default=0, max_length=1)),
                ('overs', models.CharField(default=0, max_length=1)),
                ('extras', models.CharField(default=0, max_length=2)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_bowler', to='auctions.Sold_Player')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('None', 'None'), ('Wide', 'Wide'), ('No Ball', 'No Ball')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=6)),
                ('runs', models.CharField(default=0, max_length=3)),
                ('wickets', models.CharField(default=0, max_length=1)),
                ('balls', models.CharField(default=0, max_length=2)),
                ('extras', models.CharField(default=0, max_length=2)),
                ('batting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inning_batting', to='teams.Team')),
                ('bowling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inning_bowling', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(max_length=2)),
                ('Date', models.CharField(max_length=50)),
                ('selected_to', models.CharField(choices=[('Bat', 'Bat'), ('Field', 'Field')], max_length=5)),
                ('man_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_mom', to='auctions.Sold_Player')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team2', to='teams.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team1', to='teams.Team')),
                ('toss_won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_toss', to='teams.Team')),
                ('won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_won', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.CharField(max_length=1)),
                ('super_over', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('female_over', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_ball', to='matches.Ball')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_bowler', to='auctions.Sold_Player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_innings', to='matches.Innings')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_non_striker', to='auctions.Sold_Player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='over_striker', to='auctions.Sold_Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixes', models.CharField(default=0, max_length=3)),
                ('fours', models.CharField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Wicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('None', 'None'), ('Run Out', 'Run Out'), ('Caught', 'Caught'), ('Bold', 'Bold'), ('Hit Wicket', 'Hit Wicket'), ('Stumped', 'Stumped')], max_length=15)),
                ('player1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_player1', to='auctions.Sold_Player')),
                ('player2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_player2', to='auctions.Sold_Player')),
            ],
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inning_match', to='matches.Match'),
        ),
        migrations.AddField(
            model_name='bowling_scorecard',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='matches.Innings'),
        ),
        migrations.AddField(
            model_name='batting_scorecard',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='matches.Innings'),
        ),
        migrations.AddField(
            model_name='batting_scorecard',
            name='wicket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_batsman', to='matches.Wicket'),
        ),
        migrations.AddField(
            model_name='ball',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_extra', to='matches.Extra'),
        ),
        migrations.AddField(
            model_name='ball',
            name='wicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicket_extra', to='matches.Wicket'),
        ),
    ]
