# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='man_of_match',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_mom', to='auctions.Sold_Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='selected_to',
            field=models.CharField(blank=True, choices=[('Bat', 'Bat'), ('Field', 'Field')], max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_won',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_toss', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='won',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_won', to='teams.Team'),
        ),
    ]
