# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20170301_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='man_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_mom', to='auctions.Sold_Player'),
        ),
    ]
