# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20170301_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Date',
            new_name='date',
        ),
    ]
