# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20170301_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cur_match', to='matches.Match')),
            ],
        ),
    ]
