# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_current_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innings',
            name='innings',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='first_innings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_first_inning', to='matches.Innings'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_innings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_second_inning', to='matches.Innings'),
        ),
    ]
