# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20170302_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_match',
            name='inning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_inning', to='matches.Innings'),
        ),
        migrations.AlterField(
            model_name='current_match',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_match', to='matches.Match'),
        ),
    ]
