# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_points_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points_table',
            name='lost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='nrr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='won',
            field=models.IntegerField(),
        ),
    ]
