# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20170302_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
