# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20170302_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ball_extra', to='matches.Extra'),
        ),
    ]
