# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_auto_20170302_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting_scorecard',
            name='retired',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6),
        ),
        migrations.AlterField(
            model_name='batting_scorecard',
            name='wicket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_batsman', to='matches.Wicket'),
        ),
    ]
