# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_auto_20170302_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='run',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=1),
        ),
    ]
