# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_auto_20170302_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='over',
            name='super_over',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
