# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_auto_20170302_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting_scorecard',
            name='retired',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=6),
        ),
        migrations.AlterField(
            model_name='innings',
            name='balls',
            field=models.IntegerField(default=0),
        ),
    ]
