# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_auto_20170302_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wicket_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='wicket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicket_type', to='matches.Wicket_Type'),
        ),
    ]
