# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0027_auto_20170302_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='wicket_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_extra', to='matches.Wicket'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='wicket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_extra', to='matches.Wicket_Type'),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='extras',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='overs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='wickets',
            field=models.IntegerField(),
        ),
    ]
