# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0029_auto_20170302_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_match',
            name='over',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_over', to='matches.Over'),
        ),
    ]
