# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0030_current_match_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting_scorecard',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting_scorecard',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting_scorecard',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting_scorecard',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='overs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling_scorecard',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innings',
            name='extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innings',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innings',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='over',
            name='over',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament_stats',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament_stats',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
    ]
