# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0031_auto_20170302_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowling_scorecard',
            old_name='overs',
            new_name='balls',
        ),
    ]
