# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0032_auto_20170303_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowling_scorecard',
            name='overs',
            field=models.CharField(default='0.0', max_length=3),
            preserve_default=False,
        ),
    ]
