# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0033_bowling_scorecard_overs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='over',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over_bowler', to='auctions.Sold_Player'),
        ),
        migrations.AlterField(
            model_name='over',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over_non_striker', to='auctions.Sold_Player'),
        ),
        migrations.AlterField(
            model_name='over',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='over_striker', to='auctions.Sold_Player'),
        ),
    ]
