# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0035_auto_20170303_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wicket',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_player2', to='auctions.Sold_Player'),
        ),
    ]
