# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0037_batting_scorecard_come_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='bye',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=1),
        ),
    ]
