# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='price',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
