# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='player',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
