# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20170206_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='money',
            field=models.IntegerField(default=3000),
        ),
    ]
