# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170207_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='players_cost',
            field=models.IntegerField(default=0),
        ),
    ]
