# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_player',
            name='toggle',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
