# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_sold_player_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='sold_player',
            name='toggle',
        ),
    ]
