# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20170206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_player',
            name='price',
            field=models.IntegerField(),
        ),
    ]
