# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20170301_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_player',
            name='catches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='fours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='sixes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='wickets',
            field=models.IntegerField(),
        ),
    ]
