# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20170303_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_player',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold_player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
