# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('pic', models.ImageField(upload_to='player_pics/')),
                ('phone_no', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder')], max_length=100)),
                ('prev_exp', models.TextField(blank=True)),
                ('kpl_exp', models.TextField(blank=True)),
            ],
        ),
    ]
