# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pool',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=1),
        ),
    ]
