# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='manager',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
