# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='manager',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
