# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20170120_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='kpl_exp',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='manager',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='prev_exp',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
