# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold'), ('Unsold', 'Unsold')], default='pending', max_length=10),
        ),
    ]
