# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='auction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold'), ('Unsold', 'Unsold')], default='Pending', max_length=10),
        ),
    ]
