# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20170206_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='kpl_exp',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='prev_exp',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
    ]
