# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20170206_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='auction_status',
            field=models.CharField(choices=[('pending', 'pending'), ('sold', 'sold')], default='pending', max_length=10),
        ),
    ]
