# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20170206_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['pool', 'name']},
        ),
    ]
